
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { PieChart } from "recharts";
import { Users, DollarSign, Link as LinkIcon, TrendingUp, Award, BarChart2 } from "lucide-react";

const Affiliation = () => {
  const tiers = [
    {
      name: "Bronze",
      referrals: "1-10",
      commission: "20%",
      benefits: ["Basic referral tracking", "Monthly payouts", "Email support"]
    },
    {
      name: "Silver",
      referrals: "11-50",
      commission: "25%",
      benefits: ["Advanced analytics", "Bi-weekly payouts", "Priority support", "Custom referral links"]
    },
    {
      name: "Gold",
      referrals: "51-200",
      commission: "30%",
      benefits: ["Real-time tracking dashboard", "Weekly payouts", "Dedicated account manager", "Marketing materials", "Performance bonuses"]
    },
    {
      name: "Platinum",
      referrals: "201+",
      commission: "35%",
      benefits: ["VIP support", "Daily payouts", "Co-branding opportunities", "Exclusive affiliate events", "Revenue share options"]
    }
  ];

  return (
    <div className="container py-12">
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold mb-4">Affiliate Program</h1>
        <p className="text-muted-foreground text-xl max-w-2xl mx-auto">
          Join our affiliate program and earn commissions by referring new users to BlockFin
        </p>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
        <Card className="text-center">
          <CardHeader>
            <div className="mx-auto bg-primary/10 p-4 rounded-full mb-4">
              <DollarSign className="h-8 w-8 text-primary" />
            </div>
            <CardTitle>Competitive Commissions</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Earn up to 35% commission on trading fees generated by your referrals
            </p>
          </CardContent>
        </Card>
        
        <Card className="text-center">
          <CardHeader>
            <div className="mx-auto bg-primary/10 p-4 rounded-full mb-4">
              <TrendingUp className="h-8 w-8 text-primary" />
            </div>
            <CardTitle>Lifetime Revenue</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Receive commissions for the entire duration your referrals remain active
            </p>
          </CardContent>
        </Card>
        
        <Card className="text-center">
          <CardHeader>
            <div className="mx-auto bg-primary/10 p-4 rounded-full mb-4">
              <BarChart2 className="h-8 w-8 text-primary" />
            </div>
            <CardTitle>Advanced Analytics</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Track your performance with real-time analytics and reporting tools
            </p>
          </CardContent>
        </Card>
      </div>
      
      <div className="mb-16">
        <h2 className="text-3xl font-bold text-center mb-8">Commission Tiers</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {tiers.map((tier, index) => (
            <Card key={index} className={`border-t-4 ${index === 3 ? 'border-t-primary' : ''}`}>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  {tier.name}
                  {index === 3 && <Award className="h-5 w-5 text-primary" />}
                </CardTitle>
                <CardDescription>
                  {tier.referrals} active referrals
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold text-primary mb-4">
                  {tier.commission}
                </div>
                <ul className="space-y-2 mb-6">
                  {tier.benefits.map((benefit, i) => (
                    <li key={i} className="flex items-start text-sm">
                      <svg className="h-5 w-5 text-primary shrink-0 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>
                      {benefit}
                    </li>
                  ))}
                </ul>
                {index === 3 ? (
                  <Button className="w-full">Apply Now</Button>
                ) : (
                  <Button variant="outline" className="w-full">Join Program</Button>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
      
      <div className="mb-16">
        <h2 className="text-3xl font-bold text-center mb-8">How It Works</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center">
            <div className="bg-primary/10 h-16 w-16 rounded-full flex items-center justify-center mx-auto mb-4">
              <span className="text-2xl font-bold text-primary">1</span>
            </div>
            <h3 className="text-xl font-semibold mb-2">Sign Up</h3>
            <p className="text-muted-foreground">
              Complete the affiliate application to join our program
            </p>
          </div>
          
          <div className="text-center">
            <div className="bg-primary/10 h-16 w-16 rounded-full flex items-center justify-center mx-auto mb-4">
              <span className="text-2xl font-bold text-primary">2</span>
            </div>
            <h3 className="text-xl font-semibold mb-2">Share Your Link</h3>
            <p className="text-muted-foreground">
              Promote BlockFin using your unique referral link
            </p>
          </div>
          
          <div className="text-center">
            <div className="bg-primary/10 h-16 w-16 rounded-full flex items-center justify-center mx-auto mb-4">
              <span className="text-2xl font-bold text-primary">3</span>
            </div>
            <h3 className="text-xl font-semibold mb-2">Earn Rewards</h3>
            <p className="text-muted-foreground">
              Get paid commissions based on your referrals' activity
            </p>
          </div>
        </div>
      </div>
      
      <Tabs defaultValue="join" className="mb-12">
        <TabsList className="grid w-full grid-cols-2 mb-8">
          <TabsTrigger value="join">Join Our Program</TabsTrigger>
          <TabsTrigger value="resources">Affiliate Resources</TabsTrigger>
        </TabsList>
        
        <TabsContent value="join">
          <Card>
            <CardHeader>
              <CardTitle>Become an Affiliate</CardTitle>
              <CardDescription>
                Fill out the form below to apply for our affiliate program
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label htmlFor="name" className="text-sm font-medium">Full Name</label>
                    <Input id="name" placeholder="Your name" />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="email" className="text-sm font-medium">Email</label>
                    <Input id="email" type="email" placeholder="Your email" />
                  </div>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label htmlFor="website" className="text-sm font-medium">Website (optional)</label>
                    <Input id="website" placeholder="https://your-website.com" />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="social" className="text-sm font-medium">Social Media Handle</label>
                    <Input id="social" placeholder="@username" />
                  </div>
                </div>
                
                <div className="space-y-2">
                  <label htmlFor="promotion" className="text-sm font-medium">How will you promote BlockFin?</label>
                  <textarea 
                    id="promotion" 
                    rows={4}
                    placeholder="Tell us about your promotion strategy..."
                    className="w-full min-h-[100px] rounded-md border border-input bg-background px-3 py-2 text-sm"
                  />
                </div>
                
                <div className="flex justify-end">
                  <Button>Submit Application</Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="resources">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <LinkIcon className="h-5 w-5 mr-2 text-primary" />
                  Referral Links
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="mb-4">Use your unique referral link to track referred users:</p>
                <div className="flex mb-4">
                  <Input value="https://blockfin.com/?ref=YOUR_ID" readOnly />
                  <Button variant="outline" className="ml-2">Copy</Button>
                </div>
                <p className="text-sm text-muted-foreground">
                  You can also create custom referral links for different campaigns in your affiliate dashboard.
                </p>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Users className="h-5 w-5 mr-2 text-primary" />
                  Marketing Materials
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="mb-4">Download our official marketing materials:</p>
                <div className="space-y-2">
                  <Button variant="outline" className="w-full justify-start">
                    <svg className="mr-2 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
                    BlockFin Logo Pack
                  </Button>
                  <Button variant="outline" className="w-full justify-start">
                    <svg className="mr-2 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
                    Banner Graphics
                  </Button>
                  <Button variant="outline" className="w-full justify-start">
                    <svg className="mr-2 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
                    Email Templates
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
      
      <div className="bg-primary/5 p-8 rounded-lg text-center">
        <h2 className="text-2xl font-bold mb-4">Ready to Start Earning?</h2>
        <p className="text-muted-foreground max-w-2xl mx-auto mb-6">
          Join thousands of successful affiliates who are earning passive income by referring users to BlockFin.
        </p>
        <Button size="lg">
          Apply to Affiliate Program
        </Button>
      </div>
    </div>
  );
};

export default Affiliation;
